name: PHP CI


  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
      - name: Install
        run: make install
      - name: Run linter
        run: make lint
        
